const Koa = require('koa');
const router = require('koa-router')();
const logger = require('koa-logger');
const onError = require('koa-onerror');
const bodyParser = require('koa-bodyparser');
const path = require('path');
const staticServer = require('koa-static');
var app = new Koa();
app.use(logger());
app.use(bodyParser());
app.use(staticServer(path.join(__dirname,'public')));
var article = require('./routes/article');
router.use('/article', article.routes());
var users = require('./routes/users');
router.use('/users', users.routes());
app.use(router.routes());
onError(app);
app.listen(3000);